//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                    This did not seem to encourage the witness at all: he kept shifting  from one foot to the other, looking uneasily at the Queen, and in  his confusion he bit a large piece out of his teacup instead of the  bread-and-butter.
        ///                &lt;/p&gt;
        ///
        ///                &lt;p&gt;
        ///                    Just at this moment Alice felt a very curious sensation, which puzzled  her a good deal until she made out what it was: she was beginning to  grow larger again, and she thought at first she would ge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutContentText1 {
            get {
                return ResourceManager.GetString("AboutContentText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; The Hatter&apos;s remark seemed to have no sort of meaning in it, and yet it was certainly English. &apos;I don&apos;t quite understand you,&apos; she said, as politely as she could. &apos;The Dormouse is asleep again,&apos; said the Hatter, and he poured a little hot tea upon its nose. &lt;/p&gt;
        ///                &lt;h3&gt;I don&apos;t quite understand you&lt;/h3&gt;
        ///                &lt;p&gt; The Dormouse shook its head impatiently, and said, without opening its eyes, &apos;Of course, of course; just what I was going to remark myself.&apos; &apos;Have you guessed the riddle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutContentText2 {
            get {
                return ResourceManager.GetString("AboutContentText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build your website, now!.
        /// </summary>
        internal static string AboutContentTitle1 {
            get {
                return ResourceManager.GetString("AboutContentTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ashley website template.
        /// </summary>
        internal static string AboutContentTitle2 {
            get {
                return ResourceManager.GetString("AboutContentTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kristina Kayryakova ROCKS!.
        /// </summary>
        internal static string AboutSubTitle {
            get {
                return ResourceManager.GetString("AboutSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string ContactUsButtonText {
            get {
                return ResourceManager.GetString("ContactUsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string ContactUsTitle {
            get {
                return ResourceManager.GetString("ContactUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle1.
        /// </summary>
        internal static string HomeSubTitle1 {
            get {
                return ResourceManager.GetString("HomeSubTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle2.
        /// </summary>
        internal static string HomeSubTitle2 {
            get {
                return ResourceManager.GetString("HomeSubTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle3.
        /// </summary>
        internal static string HomeSubTitle3 {
            get {
                return ResourceManager.GetString("HomeSubTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High quality translations.
        /// </summary>
        internal static string HomeTitle1 {
            get {
                return ResourceManager.GetString("HomeTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal commitment.
        /// </summary>
        internal static string HomeTitle2 {
            get {
                return ResourceManager.GetString("HomeTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simultaneous interpretation.
        /// </summary>
        internal static string HomeTitle3 {
            get {
                return ResourceManager.GetString("HomeTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string OurWorkAll {
            get {
                return ResourceManager.GetString("OurWorkAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string OurWorkCompanies {
            get {
                return ResourceManager.GetString("OurWorkCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goverment.
        /// </summary>
        internal static string OurWorkGoverment {
            get {
                return ResourceManager.GetString("OurWorkGoverment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines.
        /// </summary>
        internal static string OurWorkMagazines {
            get {
                return ResourceManager.GetString("OurWorkMagazines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest cool projects we&apos;ve been working on.
        /// </summary>
        internal static string OurWorkSubTitle {
            get {
                return ResourceManager.GetString("OurWorkSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our work.
        /// </summary>
        internal static string OurWorkTitle {
            get {
                return ResourceManager.GetString("OurWorkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0$&lt;span&gt;per month&lt;/span&gt;.
        /// </summary>
        internal static string Price1 {
            get {
                return ResourceManager.GetString("Price1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Price1EU {
            get {
                return ResourceManager.GetString("Price1EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price1row1 {
            get {
                return ResourceManager.GetString("Price1row1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price1row2 {
            get {
                return ResourceManager.GetString("Price1row2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price1row3 {
            get {
                return ResourceManager.GetString("Price1row3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price1row4 {
            get {
                return ResourceManager.GetString("Price1row4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price1row5 {
            get {
                return ResourceManager.GetString("Price1row5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price1row6 {
            get {
                return ResourceManager.GetString("Price1row6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string Price1Title {
            get {
                return ResourceManager.GetString("Price1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10$&lt;span&gt;per month&lt;/span&gt;.
        /// </summary>
        internal static string Price2 {
            get {
                return ResourceManager.GetString("Price2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Price2EU {
            get {
                return ResourceManager.GetString("Price2EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price2row1 {
            get {
                return ResourceManager.GetString("Price2row1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price2row2 {
            get {
                return ResourceManager.GetString("Price2row2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price2row3 {
            get {
                return ResourceManager.GetString("Price2row3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price2row4 {
            get {
                return ResourceManager.GetString("Price2row4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price2row5 {
            get {
                return ResourceManager.GetString("Price2row5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price2row6 {
            get {
                return ResourceManager.GetString("Price2row6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialized Translation.
        /// </summary>
        internal static string Price2Title {
            get {
                return ResourceManager.GetString("Price2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25$&lt;span&gt;per month&lt;/span&gt;.
        /// </summary>
        internal static string Price3 {
            get {
                return ResourceManager.GetString("Price3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Price3EU {
            get {
                return ResourceManager.GetString("Price3EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price3row1 {
            get {
                return ResourceManager.GetString("Price3row1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price3row2 {
            get {
                return ResourceManager.GetString("Price3row2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price3row3 {
            get {
                return ResourceManager.GetString("Price3row3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price3row4 {
            get {
                return ResourceManager.GetString("Price3row4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price3row5 {
            get {
                return ResourceManager.GetString("Price3row5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price3row6 {
            get {
                return ResourceManager.GetString("Price3row6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofreading.
        /// </summary>
        internal static string Price3Title {
            get {
                return ResourceManager.GetString("Price3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40$&lt;span&gt;per month&lt;/span&gt;.
        /// </summary>
        internal static string Price4 {
            get {
                return ResourceManager.GetString("Price4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Price4EU {
            get {
                return ResourceManager.GetString("Price4EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price4row1 {
            get {
                return ResourceManager.GetString("Price4row1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price4row2 {
            get {
                return ResourceManager.GetString("Price4row2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price4row3 {
            get {
                return ResourceManager.GetString("Price4row3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price4row4 {
            get {
                return ResourceManager.GetString("Price4row4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price4row5 {
            get {
                return ResourceManager.GetString("Price4row5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Price4row6 {
            get {
                return ResourceManager.GetString("Price4row6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretation.
        /// </summary>
        internal static string Price4Title {
            get {
                return ResourceManager.GetString("Price4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check prices.
        /// </summary>
        internal static string PricesButtonText {
            get {
                return ResourceManager.GetString("PricesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our plans.
        /// </summary>
        internal static string PricesTitle {
            get {
                return ResourceManager.GetString("PricesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegant layouts that help you organize your content in the best way.
        /// </summary>
        internal static string ServicesPanel1Content {
            get {
                return ResourceManager.GetString("ServicesPanel1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written translations.
        /// </summary>
        internal static string ServicesPanel1Title {
            get {
                return ResourceManager.GetString("ServicesPanel1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built with modern technologies like HTML5 and CSS3, SEO optimised.
        /// </summary>
        internal static string ServicesPanel2Content {
            get {
                return ResourceManager.GetString("ServicesPanel2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialized translation.
        /// </summary>
        internal static string ServicesPanel2Title {
            get {
                return ResourceManager.GetString("ServicesPanel2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible with various desktop, tablet, and mobile devices..
        /// </summary>
        internal static string ServicesPanel3Content {
            get {
                return ResourceManager.GetString("ServicesPanel3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simultaneous and consecutive interpretation.
        /// </summary>
        internal static string ServicesPanel3Title {
            get {
                return ResourceManager.GetString("ServicesPanel3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear code and documentation, base on Bootstrap 3.
        /// </summary>
        internal static string ServicesPanel4Content {
            get {
                return ResourceManager.GetString("ServicesPanel4Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legalization.
        /// </summary>
        internal static string ServicesPanel4Title {
            get {
                return ResourceManager.GetString("ServicesPanel4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are doing a couple of things you might be interested in.
        /// </summary>
        internal static string ServicesSubTitle {
            get {
                return ResourceManager.GetString("ServicesSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our services.
        /// </summary>
        internal static string ServicesTitle {
            get {
                return ResourceManager.GetString("ServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because the cheapest price is not the best price..
        /// </summary>
        internal static string UnderBannerSubTitle {
            get {
                return ResourceManager.GetString("UnderBannerSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium language services on competitive prices..
        /// </summary>
        internal static string UnderBannerTitle {
            get {
                return ResourceManager.GetString("UnderBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep in touch with us.
        /// </summary>
        internal static string UnderOurWorkText {
            get {
                return ResourceManager.GetString("UnderOurWorkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile first, truly responsive,&lt;br /&gt; based on bootstrap 3.
        /// </summary>
        internal static string UnderPricesTitle {
            get {
                return ResourceManager.GetString("UnderPricesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being a famous designer&lt;br /&gt;is like being a famous dentist&lt;br /&gt;&lt;small&gt;NOREEN MORIOKA&lt;/small&gt;.
        /// </summary>
        internal static string UnderServicesBannerText {
            get {
                return ResourceManager.GetString("UnderServicesBannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works.
        /// </summary>
        internal static string Works {
            get {
                return ResourceManager.GetString("Works", resourceCulture);
            }
        }
    }
}
